"""add remote_side and uselist to many-to-one

Revision ID: 03181e4aba67
Revises: 050afee2773a
Create Date: 2024-12-10 17:17:32.076469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03181e4aba67'
down_revision: Union[str, None] = '050afee2773a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
