"""add chat_id to message

Revision ID: 050afee2773a
Revises: cded7a22a306
Create Date: 2024-12-10 17:11:37.012745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050afee2773a'
down_revision: Union[str, None] = 'cded7a22a306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messages', 'user_chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###
