"""delete last_message_id

Revision ID: 066a2e1bae03
Revises: 7537aaa18523
Create Date: 2024-12-10 17:40:08.328141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066a2e1bae03'
down_revision: Union[str, None] = '7537aaa18523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_chats_last_message_id_fkey', 'user_chats', type_='foreignkey')
    op.drop_column('user_chats', 'last_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('last_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_chats_last_message_id_fkey', 'user_chats', 'messages', ['last_message_id'], ['id'])
    # ### end Alembic commands ###
