"""change relationships to many-to-one and backref

Revision ID: 2813173bd33b
Revises: 8f86d608f385
Create Date: 2024-12-10 17:28:26.650741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2813173bd33b'
down_revision: Union[str, None] = '8f86d608f385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
