"""add author message without relationships

Revision ID: 3f78e361576a
Revises: 5c8278d3294a
Create Date: 2024-12-10 16:03:19.149346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f78e361576a'
down_revision: Union[str, None] = '5c8278d3294a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author', sa.String(length=24), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'author')
    # ### end Alembic commands ###
