"""update chat_id

Revision ID: 40b7e9f82eca
Revises: f5cc543b566b
Create Date: 2024-12-06 20:21:50.186554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b7e9f82eca'
down_revision: Union[str, None] = 'f5cc543b566b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('chat_uuid', sa.String(), nullable=False))
    op.drop_constraint('user_chats_chat_id_key', 'user_chats', type_='unique')
    op.create_unique_constraint(None, 'user_chats', ['chat_uuid'])
    op.drop_column('user_chats', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('chat_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_chats', type_='unique')
    op.create_unique_constraint('user_chats_chat_id_key', 'user_chats', ['chat_id'])
    op.drop_column('user_chats', 'chat_uuid')
    # ### end Alembic commands ###
