"""remove indexes

Revision ID: 4e1d54e37aac
Revises: 5907b5fb7cf7
Create Date: 2024-12-09 20:41:08.440229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e1d54e37aac'
down_revision: Union[str, None] = '5907b5fb7cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_chats_unique_participants', table_name='user_chats')
    op.drop_column('user_chats', 'auth_user')
    op.drop_column('user_chats', 'participants')
    op.drop_column('user_chats', 'companion_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('companion_user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_chats', sa.Column('participants', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_chats', sa.Column('auth_user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_chats_unique_participants', 'user_chats', ['auth_user', 'companion_user'], unique=True)
    # ### end Alembic commands ###
