"""add index to json

Revision ID: 5907b5fb7cf7
Revises: d748c2a650a4
Create Date: 2024-12-09 20:34:17.967354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5907b5fb7cf7'
down_revision: Union[str, None] = 'd748c2a650a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('auth_user', sa.String(), nullable=True))
    op.add_column('user_chats', sa.Column('companion_user', sa.String(), nullable=True))
    op.create_index('ix_user_chats_unique_participants', 'user_chats', ['auth_user', 'companion_user'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_chats_unique_participants', table_name='user_chats')
    op.drop_column('user_chats', 'companion_user')
    op.drop_column('user_chats', 'auth_user')
    # ### end Alembic commands ###
