"""add participants

Revision ID: 64bcd4f4acc6
Revises: cbe34c8e67bc
Create Date: 2024-12-07 08:38:44.952622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64bcd4f4acc6'
down_revision: Union[str, None] = 'cbe34c8e67bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('participants', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chats', 'participants')
    # ### end Alembic commands ###
