"""change relationships to many-to-one and remote_sides

Revision ID: 7537aaa18523
Revises: fa1f4855ca99
Create Date: 2024-12-10 17:35:07.505398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7537aaa18523'
down_revision: Union[str, None] = 'fa1f4855ca99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
