"""add json participants back

Revision ID: a7e72b33aef0
Revises: 4e1d54e37aac
Create Date: 2024-12-09 20:41:52.910735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e72b33aef0'
down_revision: Union[str, None] = '4e1d54e37aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('participants', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chats', 'participants')
    # ### end Alembic commands ###
