"""add json participants

Revision ID: ad375de6ab64
Revises: df9870745896
Create Date: 2024-12-09 17:18:11.243579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad375de6ab64'
down_revision: Union[str, None] = 'df9870745896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_chats', 'participants',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_chats', 'participants',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###
