"""delete chat_id

Revision ID: cbe34c8e67bc
Revises: 40b7e9f82eca
Create Date: 2024-12-07 08:15:52.618854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe34c8e67bc'
down_revision: Union[str, None] = '40b7e9f82eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_chats_chat_uuid_key', 'user_chats', type_='unique')
    op.drop_column('user_chats', 'chat_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('chat_uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_chats_chat_uuid_key', 'user_chats', ['chat_uuid'])
    # ### end Alembic commands ###
