"""delete auth_user and companion

Revision ID: df9870745896
Revises: 64bcd4f4acc6
Create Date: 2024-12-07 08:41:20.311338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9870745896'
down_revision: Union[str, None] = '64bcd4f4acc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_chats_auth_user_fkey', 'user_chats', type_='foreignkey')
    op.drop_constraint('user_chats_companion_fkey', 'user_chats', type_='foreignkey')
    op.drop_column('user_chats', 'companion')
    op.drop_column('user_chats', 'auth_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chats', sa.Column('auth_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_chats', sa.Column('companion', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_chats_companion_fkey', 'user_chats', 'users', ['companion'], ['id'])
    op.create_foreign_key('user_chats_auth_user_fkey', 'user_chats', 'users', ['auth_user'], ['id'])
    # ### end Alembic commands ###
