"""change relationships to many-to-one and back_populates

Revision ID: e16d5b93e226
Revises: 2813173bd33b
Create Date: 2024-12-10 17:30:48.684161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16d5b93e226'
down_revision: Union[str, None] = '2813173bd33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
