"""change relationships to many-to-one and fkeys

Revision ID: ea0f22eb0b9c
Revises: e16d5b93e226
Create Date: 2024-12-10 17:31:52.134024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0f22eb0b9c'
down_revision: Union[str, None] = 'e16d5b93e226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
