"""change relationships to many-to-one and remote_sides

Revision ID: fa1f4855ca99
Revises: ea0f22eb0b9c
Create Date: 2024-12-10 17:33:22.860688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1f4855ca99'
down_revision: Union[str, None] = 'ea0f22eb0b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
